### ISSUE TITLE
Unable to build on Android with react-navigation 3.11.1 and react-native 0.59.10

### ISSUE THREAD

**Issue by thekevinbrown** [react-navigation/react-navigation#6109]
### Current Behavior

When building on Android I get the following:

```
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:3: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:4: error: package androidx.fragment.app does not exist
import androidx.fragment.app.Fragment;
                            ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:5: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentActivity;
                            ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:6: error: package androidx.fragment.app does not exist
import androidx.fragment.app.FragmentTransaction;
                            ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:3: error: cannot find symbol
import androidx.annotation.Nullable;
                          ^
  symbol:   class Nullable
  location: package androidx.annotation
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:4: error: package androidx.fragment.app does not exist
import androidx.fragment.app.Fragment;
                            ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:27: error: cannot find symbol
  private @Nullable FragmentTransaction mCurrentTransaction;
                    ^
  symbol:   class FragmentTransaction
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:82: error: cannot find symbol
  private FragmentActivity findRootFragmentActivity() {
          ^
  symbol:   class FragmentActivity
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:108: error: cannot find symbol
  private FragmentTransaction getOrCreateTransaction() {
          ^
  symbol:   class FragmentTransaction
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:41: error: cannot find symbol
  private final Fragment mFragment;
                ^
  symbol:   class Fragment
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:96: error: cannot find symbol
  protected Fragment getFragment() {
            ^
  symbol:   class Fragment
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:3: error: package androidx.lifecycle does not exist
import androidx.lifecycle.Lifecycle;
                         ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:4: error: package androidx.lifecycle does not exist
import androidx.lifecycle.LifecycleObserver;
                         ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:5: error: package androidx.fragment.app does not exist
import androidx.fragment.app.Fragment;
                            ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:17: error: cannot find symbol
  public static @Nullable Fragment findNearestScreenFragmentAncestor(View view) {
                          ^
  symbol:   class Fragment
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:28: error: cannot find symbol
  private Map<View, Lifecycle> mViewToLifecycleMap = new HashMap<>();
                    ^
  symbol:   class Lifecycle
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:46: error: cannot find symbol
  public <T extends View & LifecycleObserver> void register(T view) {
                           ^
  symbol:   class LifecycleObserver
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:55: error: cannot find symbol
  public <T extends View & LifecycleObserver> void unregister(T view) {
                           ^
  symbol:   class LifecycleObserver
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:19: error: cannot find symbol
  public static class ScreenFragment extends Fragment {
                                             ^
  symbol:   class Fragment
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:27: error: cannot find symbol
  private @Nullable FragmentTransaction mCurrentTransaction;
           ^
  symbol:   class Nullable
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:42: error: cannot find symbol
  private @Nullable ScreenContainer mContainer;
           ^
  symbol:   class Nullable
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:80: error: cannot find symbol
  public void setLayerType(int layerType, @Nullable Paint paint) {
                                           ^
  symbol:   class Nullable
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:88: error: cannot find symbol
  protected void setContainer(@Nullable ScreenContainer mContainer) {
                               ^
  symbol:   class Nullable
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:92: error: cannot find symbol
  protected @Nullable ScreenContainer getContainer() {
             ^
  symbol:   class Nullable
  location: class Screen
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:35: error: cannot find symbol
                             @Nullable ViewGroup container,
                              ^
  symbol:   class Nullable
  location: class ScreenFragment
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:36: error: cannot find symbol
                             @Nullable Bundle savedInstanceState) {
                              ^
  symbol:   class Nullable
  location: class ScreenFragment
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:98: error: cannot find symbol
    while (!(context instanceof FragmentActivity) && context instanceof ContextWrapper) {
                                ^
  symbol:   class FragmentActivity
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:101: error: cannot find symbol
    if (!(context instanceof FragmentActivity)) {
                             ^
  symbol:   class FragmentActivity
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:105: error: cannot find symbol
    return (FragmentActivity) context;
            ^
  symbol:   class FragmentActivity
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:129: error: cannot find symbol
    FragmentTransaction transaction = getOrCreateTransaction();
    ^
  symbol:   class FragmentTransaction
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainer.java:130: error: cannot find symbol
    Fragment fragment = screen.getFragment();
    ^
  symbol:   class Fragment
  location: class ScreenContainer
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.java:33: error: method does not override or implement a method from a supertype
    @Override
    ^
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:38: error: cannot find symbol
    Fragment parent = findNearestScreenFragmentAncestor(view);
    ^
  symbol:   class Fragment
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:39: error: cannot find symbol
    if (parent != null && view instanceof LifecycleObserver) {
                                          ^
  symbol:   class LifecycleObserver
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:40: error: cannot find symbol
      Lifecycle lifecycle = parent.getLifecycle();
      ^
  symbol:   class Lifecycle
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:41: error: cannot find symbol
      lifecycle.addObserver((LifecycleObserver) view);
                             ^
  symbol:   class LifecycleObserver
  location: class LifecycleHelper
[project directory]/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/LifecycleHelper.java:56: error: cannot find symbol
    Lifecycle lifecycle = mViewToLifecycleMap.get(view);
    ^
  symbol:   class Lifecycle
  location: class LifecycleHelper
```

### Expected Behavior

I'd expect to be able to build on React Native 59 with a particular version of `react-navigation`, but it appears that `react-native-screens` have pushed a patch update to support React Native 60, which then breaks everyone on 59 when they haven't even changed their version of `react-navigation` at all, as `react-native-screens` isn't specified as a specific version in `@react-navigation/native`'s `package.json` file:

https://github.com/react-navigation/native/blob/master/package.json#L95

What I'd expect to see is either:
 - a version of `react-navigation` released with a definitive pinned `react-native-screens` version so we can depend on it when using React Native 59 and successfully build.
- the release of `react-native-screens` with AndroidX support released following semver so that it doesn't break everyone. I'll also lodge an issue there, but I suspect since they're still in `alpha` they'll say that any alpha update can be a breaking update.

### How to reproduce

Install and build the latest version of `react-navigation` in a React Native 59 project.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.59.10
| node             | 10.15.3
| npm or yarn      | npm

**Comment by thekevinbrown** [comment]
Looks like the issue [has already been logged over there](https://github.com/kmagiera/react-native-screens/issues/126), it'd be nice to save people the hassle of encountering this if possible.

**Comment by thekevinbrown** [comment]
For anyone finding this in the future, you can fix your build by running:

```
$ npm i react-native-screens@1.0.0-alpha.22 --save-exact
```

**Comment by matthamil** [comment]
Closing since this is an issue with [react-native-screens](https://github.com/kmagiera/react-native-screens). You may want to check out the [jetifier tool](https://developer.android.com/studio/command-line/jetifier) if you are using libraries that are not compatible with AndroidX yet.

**Comment by matthamil** [comment]
https://github.com/mikehardy/jetifier  is also another item to check out

**Comment by matthamil** [comment]
I misread the original issue--you will need to upgrade to RN 60+ to have AndroidX support.
