### ISSUE TITLE
TypeError: undefined is not a function evaluating 'navigation.getChildNavigation(route.key)' after update from 2.2.5 to 2.3.0

### ISSUE THREAD

**Issue by Dimous** [react-navigation/react-navigation#4481]
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

![screenshot_1528778986](https://user-images.githubusercontent.com/283939/41270729-3d03c434-6e50-11e8-9769-2a0af21e4606.png)

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

To work as its working with 2.2.5

![screenshot_1528779978](https://user-images.githubusercontent.com/283939/41271145-3317f7b8-6e52-11e8-8896-6f66438a5ca6.png)

### How to reproduce

Update from 2.2.5 to 2.3.0 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.0
| react-native     | next
| node             | 8.11.2
| npm or yarn      | 1.7.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by jigaryadav** [comment]
i am having the same issue

**Comment by sea13502** [comment]
i encounter the same problem.
![default](https://user-images.githubusercontent.com/1728521/41279578-738a244e-6e5f-11e8-9c33-8614692cfefb.png)

**Comment by SemperChen** [comment]
i am having the same issue

**Comment by rafaelmotta** [comment]
My routes are integrated with redux as well and I start to get the same error after migrating to v2.3.0.

**Comment by caciobanita** [comment]
Same problem, my version was 2.2.4, update to v2.3.0. I have Downgrade to v2.2.0 but no luck.

**Comment by stefanocdn** [comment]
Same issue here with react-navigation 2.3.0 after upgrading from 2.2.5 (working on 2.2.5).

**Comment by brentvatne** [comment]
sounds like this is happening with redux integration, we will look into it

**Comment by brentvatne** [comment]
I updated the release notes:

**Please note that this update is not yet compatible with react-navigation-redux-helpers!** If you integrate your navigation state with Redux [for some reason](https://github.com/react-navigation/rfcs/issues/14), you will need to stay on 2.2.5 until react-navigation-redux-helpers is updated to work with 2.3.0. You can follow the thread here: https://github.com/react-navigation/react-navigation/issues/4481

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-redux-helpers/pull/37 - this will fix is when @Ashoat has time to review and publish update. docs update is ready too: https://github.com/react-navigation/react-navigation.github.io/commit/f6b23fee2aa3369f0231f86779d2f54cdecb2469

I do want to take a moment to point out these two paragraphs I updated in the intro to the redux integration docs:

> Some folks like to have their navigation state stored in the same place as the rest of their application state. *Think twice before you consider doing this, there is an incredibly good chance that you do not need to do this!*. Storing your React Navigation state in your own Redux store is likely to give you a very difficult time if you don't know what you're doing, and support for Redux integration is being depreacted.

> **In the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work**. It may continue to work either by coincidence or will of the community, but it will not be tested against or considered when making any design decisions for the library.

this may be a good time for you to migrate your app away from using redux to store navigation state. if you have questions about specific parts that you have trouble with, please post them to this thread: https://github.com/react-navigation/react-navigation/issues/4490

**Comment by Ashoat** [comment]
Hey folks, `react-navigation-redux-helpers@2.0.0-beta.0` should solve the issues here for the time being. Please see [https://github.com/react-navigation/react-navigation-redux-helpers/issues/36] for details.

**Comment by proutek** [comment]
We are working on an app where we have TabNavigator with StackNavigators inside each tab.

TabNavigator
    -> AStack
    -> BStack
    -> CStack

Somewhere on CStack user can make action which invalidates some data on AStack screen and BStack screen so we need to reset  only AStack and BStack without resetting CStack and without animation so user stays inside of CStack where he was. I tried to reset stacks but failed. Last thing I'm trying is to fiddle directly with navigation state in redux and modify navigation state in one step.

I'm not sure if this is correct approach but documentation is not helping at all how to do this without redux.

**Comment by francisrod01** [comment]
To solved it see below:

**Instead:**

```
-    "react-navigation": "^2.0.1",
-    "react-navigation-redux-helpers": "^1.0.7",
```

**After:**

```
+    "react-navigation": "^2.3.1",
+    "react-navigation-redux-helpers": "^2.0.1",
```

**Comment by mkchx** [comment]
Having the same issue after updating to version **2.3.1** but using **mobx helpers** instead of **redux helpers**

**Comment by gulllberg** [comment]
Same problem here, passing navigation state which is self-controlled (similar idea to redux, but not actually using that or react-navigation-redux-helpers). Adding a dummy getChildNavigation function to navigation caused new problems, so had to downgrade.

**Comment by brentvatne** [comment]
this is updated https://reactnavigation.org/docs/en/redux-integration.html

**Comment by gulllberg** [comment]
@brentvatne 

I saw the update and was sorry to do so. When looking for a navigation library we wanted something we could control the state of (to for example achieve hot reloading). Most libraries we looked at were very controlling - but we were happy to see that react-navigation allowed for controlling by supplying state.

Anyway, I understand that you have a tough workload and appreciate the good job you’ve done, but it would be sad to see this functionality lost from the one library that seemed to have it (and which is recommended by react-native).

**Comment by francisrod01** [comment]
Pay attention to next: `Warning: in the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work.`

**Comment by dann1609** [comment]
@caciobanita how did you do the downgrade?

**Comment by jigaryadav** [comment]
@dann1609 change package version in package.js and do `npm i`

**Comment by dann1609** [comment]
@jigaryadav this won't work. You can check version using `npm list <package name>`. you will see that version installed mismatch from you choose. 

You need to handle run in command prompt npm I <package name>@<version>

**Comment by praveennamdev** [comment]
pleas help me how to create navigation drawer using expo and react native 0.58

**Comment by Hannibal2** [comment]
Have the same problem now with my old project. Is there any way to wun my old project without changing structure?

**Comment by PratikG9** [comment]
Facing same problem
