### ISSUE TITLE
Custom Transitioner and addListener

### ISSUE THREAD

**Issue by rodan-lewarx** [react-navigation/react-navigation#3558]
### Current Behavior

Hi, I have a custom transitioner navigator inside a stack navigator. inside this custom transitioner is another stacknavigator. When I upgrade to 1.1.1 and connect navigation to redux as written in updated instructions this transitioner throws an error when I try to navigate to the stacknavigator inside it. It throws the TypeError: addListener is not a function. When I replace this custom transitioner with tabnavigator or stacknavigator it works so I think this isn not connected to connecting to redux. Did something change in Transitionar usage? Should I handle addListener there specifically?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.1
| react-native     | 0.52

**Comment by maslianok** [comment]
What was the problem? I have the same issue...

**Comment by brentvatne** [comment]
@maslianok - please create a new issue and follow the template if you have this problem

**Comment by endoooo** [comment]
@maslianok maybe this can help: https://github.com/react-navigation/react-navigation.github.io/issues/131
