### ISSUE TITLE
RN: 0.60.0 compile error: "import android.support.v4.util.Pools" problem

### ISSUE THREAD

**Issue by ezranbayantemur** [react-navigation/react-navigation#6074]
I'm trying to install react-navigation package to my project. I did all instructions on [here](https://reactnavigation.org/docs/en/getting-started.html#installation) and getting error while compiling.
react-navigation && gesture-handler works on 0.59.10 perfectly but had problems on 0.60.0

I create a dummy project to test the package and getting these errors.

**package.json :** 
-     "jetifier": "^1.6.2",
-     "react": "16.8.6",
-     "react-native": "0.60.0",
-     "react-native-gesture-handler": "^1.3.0",
-     "react-navigation": "^3.11.0"

**error output:**
> react-native run-android
> info JS server already running.
> info Installing the app...
> 
> > Task :react-native-gesture-handler:compileDebugJavaWithJavac
> 
> > Task :react-native-gesture-handler:compileDebugJavaWithJavac FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
> 20 actionable tasks: 20 executed
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
> import android.support.v4.util.Pools;
>                               ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:19: error: package Pools does not exist
>   private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
>                             ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:3: error: package android.support.v4.util does not exist
> import android.support.v4.util.Pools;
>                               ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:19: error: package Pools does not exist
>   private static final Pools.SynchronizedPool<RNGestureHandlerStateChangeEvent> EVENTS_POOL =
>                             ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:20: error: package Pools does not exist
>           new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
>                    ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:20: error: package Pools does not exist
>           new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
>                    ^
> Note: C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 6 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BU�LD FAILED in 1m 12s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
> import android.support.v4.util.Pools;
>                               ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:19: error: package Pools does not exist
>   private static final Pools.SynchronizedPool<RNGestureHandlerEvent> EVENTS_POOL =
>                             ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:3: error: package android.support.v4.util does not exist
> import android.support.v4.util.Pools;
>                               ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:19: error: package Pools does not exist
>   private static final Pools.SynchronizedPool<RNGestureHandlerStateChangeEvent> EVENTS_POOL =
>                             ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEvent.java:20: error: package Pools does not exist
>           new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
>                    ^
> C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerStateChangeEvent.java:20: error: package Pools does not exist
>           new Pools.SynchronizedPool<>(TOUCH_EVENTS_POOL_SIZE);
>                    ^
> Note: C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 6 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-gesture-handler:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BU�LD FAILED in 1m 12s
> 
>     at checkExecSyncError (child_process.js:616:11)
>     at execFileSync (child_process.js:634:13)
>     at runOnAllDevices (C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:75:39)
>     at buildAndRun (C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:137:41)
>     at then.result (C:\Users\ezran\Desktop\SADELABS\dummyProject\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:103:12)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Thanks

**Comment by satya164** [comment]
Please provide a proper repro according to the issue template.

**Comment by jivtesh813** [comment]
@ezranbayantemur  - Please see my answer at link below. Follow steps exactly as I mentioned
[https://github.com/react-navigation/react-navigation/issues/6066]

**Comment by ricbermo** [comment]
@ezranbayantemur I used to have this issue. I think it may be related to AndroidX support. This is what I did.

1. uninstalled react-navigation and gestures handler
2. installed jetifier: `yarn add --dev jetifier`
3. added the post-install script: `"postinstall": "jetify"`
4. added the react-native.config.js with the auto-linking ignore config.
5. re-installed react-navigation and gestures handler. Here´s where I think the fix happens.
6. run the project. it worked w/o issues.

**Comment by satya164** [comment]
Closing due to no repro

**Comment by algera** [comment]
@ezranbayantemur can confirm that I also had this issue and applying @ricbermo suggestions got through it.  I ran a simplified approach:
1.  `yarn remove react-navigation`
2.  `yarn remove react-native-gesture-handler`
3.  Added to `package.json`
```
  "scripts": {
    ...
    "postinstall": "jetify"
  },
```
4.  `yarn add react-navigation`
5.  `yarn add react-native-gesture-handler`

`react-native run-android`
