### ISSUE TITLE
After updated to 2.0.4, popToTop function stopped working

### ISSUE THREAD

**Issue by afshin-hoseini** [react-navigation/react-navigation#4418]
### Current Behavior

- What code are you running and what is happening?

I've written a navigation service to access navigator in all places and was working fine, as described in documents.
After I updated to 2.0.4, calling the following method

```
static popToTop(key : string) {

      this._navigator.dispatch(

        NavigationActions.popToTop({
          key : key
        })
      )
    }
```
results in this exception:

> _reactNavigation.NavigationActions.popToTop is not a function

### Expected Behavior

Calling the `popToTop(null)` must put back the root component on the screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.55.4
| node             |6.9.4
| npm or yarn      | 16.0.4

**Comment by brentvatne** [comment]
it's under StackActions.

**Comment by afshin-hoseini** [comment]
Thanks

**Comment by wiadev** [comment]
@brentvatne props.navigation.dispatch(StackActions.popToTop()); doesn't trigger the render().

when I go back to screen, I wanna initial the state values. how can I implement this?
