### ISSUE TITLE
Cannot read property 'setNativeProps' of undefined

### ISSUE THREAD

**Issue by veljkomatic** [react-navigation/react-navigation#1584]
I have
```js
 TabNavigator({
     user: {
        screen: StackNavigator ({
           userSetting: { screen: UserSetting }
       })
     },
     shop: {
         screen: StackNavigator ({
             shopScreen: { screen: Shop}
         }, {
           navigationOptions: {
            tabBarVisible: false,
          }
        })
     },
     support: {
        screen: StackNavigator ({
           supportScreen: { screen: Support}
       })
     }
```

So I set tabBarVisible false on shop child element...but I cant navigate on support it crashes withCannot read property 'setNativeProps' of undefined

**Comment by EslamNasser** [comment]
I'm having the same problem with a similar setup.
Anybody got a solution to this?

**Comment by josephrstraub** [comment]
+1 

Works on Android but not iOS

**Comment by EslamNasser** [comment]
@josephrstraub how did you get it to work on android?

**Comment by romanenko** [comment]
I have the same issue with the similar setup: it occurs on switching between tabs, when one of the tab has `tabBarVisible: false`. And I'm also having this error only in iOS.

**Comment by vqc** [comment]
It seems like an error _is not_ thrown when the screen you are navigating too also has the tab bar hidden.

**Comment by hyubs** [comment]
👍  Encountered this issue too. Commenting out the `tabBarVisible: false` fixes the issue. Using iOS simulator and react-navigation@1.0.0-beta.9.

(though I still need to figure out a workaround to hide the tab bar)

**Comment by valetarton** [comment]
I also encountered this issue and resolved it with taking away the tabBarVisible: false
Though I might add this issue came up when I both set route config dynamically AND statically

**Comment by HeKnOw** [comment]
Can confirm issue is happening as described, and removing tabBarVisible "resolves" the issue

**Comment by zinoviev** [comment]
+1 If it's intended behavior will be nice to have noted in docs

**Comment by doomsower** [comment]
Have same problems with master branch
For me unstable workaround is to add setTimeout in componentDidUpdate in TabViewPagerPan in `node_modules/react-navigation/node_modules/react-native-tab-view` to
```js
  componentDidUpdate(prevProps: Props<T>) {
    if (prevProps.navigationState.index !== this.props.navigationState.index) {
      setTimeout(this._transitionTo, 0, this.props.navigationState.index);
    }
  }
```
I think this is what happening: TabBar from `react-navigation` and TabViewPagerPan are both children of TabViewAnimated and they share animated value for nav index (TabViewAnimated.state.position). However, when nav state changes, it is not TabViewAnimated who starts animated transition, but  TabViewPagerPan. It does so in its own componentDidUpdate, but because TabBar is not its child, it is not mounted yet.

I also would like to know, if it is intended behavior (i.e. `react-native-tab-view` assumes that footer/header doesn't get mounted and unmounted). If it is so, the correct workaround is to manage TabBar visibility from inside your own custom TabBar wrapper.

**Comment by mcampsall** [comment]
I am getting the same error when switching between a tab that hides the tabBar and another that shows the tabBar. Everything works fine if both tabs use the same `tabBarVisible` value.

`Can't read property 'setNativeProps' of undefined`

**Comment by mariotacke** [comment]
Running into the same issue right now. @doomsower, can you give an example of the TabBar wrapper that you mentioned? Maybe we can reset the `tabBarVisible` option to `true` right before we navigate?

**Comment by doomsower** [comment]
I need this behavior in different tab views, so I wrote this.
```jsx
const styles = StyleSheet.create({
  hidden: {
    height: 0,
    opacity: 0,
  },
});

const TabBarFactory = (ignoreIndices: number[] = []) => {

  const TabBar: React.StatelessComponent<Props> = (props) => {
    const { navigationState } = props;
    const hidden = ignoreIndices.includes(navigationState.index);
    const style = hidden ? styles.hidden : undefined;
    return (
      <View collapsable={false} style={style}>
        <TabBarBottom {...props} />
      </View>
    );
  };

  return TabBar;

};
```
I also use TabBarBottom on both platforms.

**Comment by mcampsall** [comment]
This worked a charm for me:

```import React, { Component } from 'react';
import { Animated } from 'react-native';
import { TabView, TabBarBottom } from 'react-navigation';

const TAB_BAR_OFFSET = -60;

export default class MyTabBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      offset: new Animated.Value(0),
    };
  }

  componentWillReceiveProps(props) {
  const newState = props.navigation.state;
  const newRoute = newState.routes[newState.index];

  if (newRoute.key === 'Home') {
    // Animated.timing(this.state.offset, { toValue: TAB_BAR_OFFSET, duration: 200 }).start();
    this.state.offset.setValue(TAB_BAR_OFFSET);
  } else {
    // Animated.timing(this.state.offset, { toValue: 0, duration: 200 }).start();
    this.state.offset.setValue(0);
  }
}

  render() {
    return (
      <TabView.TabBarBottom
        {...this.props}
        jumpToIndex={index => {
          const { dispatch, state } = props.navigation

          if (state.index === index) {
            const stackRouteName = ['Tab1', 'Tab2', 'Tab3', 'Tab1'][index]

            dispatch(NavigationActions.reset({
              index: 0,
              actions: [NavigationActions.navigate({ routeName: stackRouteName })],
            }))
          } else {
            jumpToIndex(index)
          }
        }}
        style={[styles.container, { bottom: this.state.offset }]}
        />
        // <TabBarBottom {...this.props} style={[styles.container, { bottom: this.state.offset }]}/>
    );
  }
}



const styles = {
  container: {
    overflow: 'hidden',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    elevation: 8,
  },
};

**Comment by gusgard** [comment]
Based on @doomsower idea, I made a PR  #2101 . It would great to have some feedback and more testing, branch: https://github.com/gusgard/react-navigation.git#patch-1

@veljkomatic @mcampsall @EslamNasser

**Comment by cooperka** [comment]
I get the same issue as the OP (`Cannot read property 'setNativeProps' of undefined`) when rapidly changing the items in the tab bar (this currently happens during login in my app; the tabs all go away while loading user profile, then new tabs appear soon after).

Interestingly, setting `animationEnabled: true` prevents the error 👍. The PR #2101 didn't change anything for me, but I have a different cause than most other commenters here; it would be good if someone else could test out that PR.

**Comment by cooperka** [comment]
Here's [my workaround](https://github.com/cribspot/react-native-tab-view/commit/16721866e4ea1ae493adc7070f2d0a714aca0a22?w=1) (very simple change to add a 10ms delay) and [associated update to react-navigation](https://github.com/cribspot/react-navigation/commit/02a12045ef50550fcec5187466cedd0cb206d259) if anyone wants to use it in their app. It's not PR-worthy since it's just a hacky workaround, but at least it works.

**Comment by lslvxy** [comment]
mark

**Comment by namnv16** [comment]
This bug will fixed when I set animationEnabled = false for TabNavigator

**Comment by lucasbento** [comment]
I'm getting this error **only when I build the app on release mode**, the screens that I'm testing are not using `TabNavigator`:

```
this._component.setNativeProps is not a function. (In 'this._component.setNativeProps(e)', 'this._component.setNativeProps' is undefined)
2017-11-06 12:05:55.048 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: this._component.setNativeProps is not a function. (In 'this._component.setNativeProps(e)', 'this._component.setNativeProps' is undefined)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I found out that the error is coming from https://github.com/react-community/react-navigation/blob/d1c434b54c73b6ed17b1642acd6646fbca92c92e/src/views/CardStack/PointerEventsContainer.js#L86 commenting out that same line gets rid of it.

**Comment by jwrubel** [comment]
For those who encounter this issue, I was able to get this working by manually toggling visibility of the tabbar right before navigation, as @cooperka describes in [this comment](https://github.com/react-navigation/react-navigation/issues/958#issuecomment-324635038)

**Comment by austinhale** [comment]
Definitely still an issue. We fixed this with our own hack of navigating to a screen where `tabBarVisible = true` and then quickly navigating to the screen we originally wanted to end up at. The process is hidden from the user by a full screen modal with a half second loading animation.

**Comment by brentvatne** [comment]
if someone wants to dig in and submit a PR for a fix that would be great. even sharing a full working example would be good.

**Comment by gusgard** [comment]
@brentvatne Could you review this PR https://github.com/react-navigation/react-navigation/pull/2101 ? Is working with version `1.0`

**Comment by AbhishekCode** [comment]
Anyone know whats the solution for this? I'm using 1.5.9. 

In earlier version i could enable animation and overwrite configureTransition with 10 ms duration, but with new its not working now.

**Comment by AbhishekCode** [comment]
For now instead of setting tabBarVisible false, I am setting style of tabbar absolute. 
```
{
    position: 'absolute',
    bottom: -100
}
```
this solves the issue for now.
