### ISSUE TITLE
console.js:614 Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

### ISSUE THREAD

**Issue by mushthak02** [react-navigation/react-navigation#12422]
### Current behavior

console.js:614 Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

### Expected behavior

console.js:614 Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

### Reproduction

console.js:614 Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined)

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by mushthak02** [comment]
@react-native-masked-view/masked-view": "^0.3.2",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/material-top-tabs": "^7.1.0",
    "@react-navigation/native-stack": "^7.2.0",
    "@react-navigation/stack": "^7.1.0",

**Comment by floodsterdev** [comment]
I am getting same issue. How to fix it?

    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.1",


These are error I am facing
Warning: TypeError: _reactNative.BackHandler.removeEventListener is not a function (it is undefined) console.js:614
 Warning: TypeError: unsubscribe is not a function (it is Object) console.js:614

**Comment by yjshin229** [comment]
Same here. This started happening after upgrading RN to 0.77

**Comment by mhaf4krr** [comment]
Same here, stuck here.

**Comment by jankosecki** [comment]
I don't think this repository has any reference to `BackHandler.removeEventListener` anymore. Are you sure you're not using `useBackHandler` from https://github.com/react-native-community/hooks?

**Comment by VoidBGS** [comment]
The cause of this error can be found in this [commit](https://github.com/facebook/react-native/commit/44d619414c1de3dbf17a421afa8dbcec7cdab025), in **react-native v0.77.0**, that removes the `BackHandler.removeEventListener` function completely. 

They have mentioned it in the commit message.
> This can be a breaking change for some third-party modules.

This error can be caused by:
1. Trying to use the removed function somewhere in **your code** and getting an undefined error.
2. An outdated package that is trying to use the removed function and getting an undefined error.

I looked into it and as @jankosecki mentioned, this repository has no reference to the removed function. Except in `packages\native\src\useBackButton.native.tsx` and `packages\drawer\src\utils\addCancelListener.native.tsx`. Though I am not sure if this is relevant.

I recommend going through your code and used packages and seeing where the removed function is used and acting accordingly.

**Comment by gautamsamyak** [comment]
same issue

**Comment by viljamik** [comment]
For me, patching react-native-community/hooks with this PR fixed the issue: https://github.com/react-native-community/hooks/pull/410

**Comment by PhamQuyet1606** [comment]
same issue

**Comment by jenny-chiang** [comment]
same issue

**Comment by TheoNikos** [comment]
same

**Comment by gautamsamyak** [comment]
same issue

**Comment by lukaqll** [comment]
same issue

**Comment by PhamQuyet1606** [comment]
> same issue

I saw that my problem relates to the "react native modal". After following up on this issue [https://github.com/react-native-modal/react-native-modal/issues/781](url), I have fixed this issue.

**Comment by satya164** [comment]
React Navigation is not using `BackHandler.removeEventListener` so I'm closing the issue. Please find the library that's causing the error and open the issue there.

**Comment by petros-g** [comment]
If you are using RN 0.77.0, they deprecated BackHandler.removeEventListener. So the fix for me is to replace every **".removeEventListener"** code I had in the app with the following: 

 ```
const backHandler = BackHandler.addEventListener(
      'hardwareBackPress',
      backAction,
    );

    return () => backHandler.remove();
```

**Comment by Yogesh-yo01** [comment]
I'm facing the same error🚫, but I have resolved  it now 🔥 .

If you don't need BackHandler ❌, you can comment out the following code:

componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPress);
    if (this.didUpdateDimensionsEmitter) {
        this.didUpdateDimensionsEmitter.remove();
    }
    if (this.interactionHandle) {
        InteractionManager.clearInteractionHandle(this.interactionHandle);
        this.interactionHandle = null;
    }
}

Path: node_modules/react-native-modal/dist/modal.js

**Comment by sultanularefin** [comment]
I am getting this error, while using this package, "@expo/react-native-action-sheet": "^3.14.0".

While pressing on **one action item** or outside the **action sheet**. my React native versions are like below:

  "@expo/react-native-action-sheet": "^3.14.0",
  "react": "19.0.0",
  "react-native": "0.78.0",

**Comment by Samide47** [comment]
I've found that I'm using native base Select it was implementing _reactNative.BackHandler.removeEventListener

**Comment by singlamanik12** [comment]
Upgrade react-native-modal package to latest, worked for me

**Comment by gabrielmacedo102** [comment]
after removing **BackHandler.removeEventListener** in RN 0.77+

You will need to remove all calls to  **BackHandler.removeEventListener** in your imported libraries, I was using native-base:

path: ..\node_modules\native-base\src\hooks\useKeyboardDismissable.ts

old content:
```
export const useKeyboardDismissable = ({ enabled, callback }: IParams) => {
  React.useEffect(() => {
    let cleanupFn = () => {};
    if (enabled) {
      cleanupFn = keyboardDismissHandlerManager.push(callback);
    } else {
      cleanupFn();
    }
    return () => {
      cleanupFn();
    };
  }, [enabled, callback]);

  useBackHandler({ enabled, callback });
};

export function useBackHandler({ enabled, callback }: IParams) {
  useEffect(() => {
    let backHandler = () => {
      callback();
      return true;
    };
    if (enabled) {
      BackHandler.addEventListener('hardwareBackPress', backHandler);
    } else {
      BackHandler.removeEventListener('hardwareBackPress', backHandler);
    }
    return () =>
      BackHandler.removeEventListener('hardwareBackPress', backHandler);
  }, [enabled, callback]);
}
```

solution:
```
export const useKeyboardDismissable = ({ enabled, callback }: IParams) => {
  React.useEffect(() => {
    let cleanupFn = () => {};
    if (enabled) {
      cleanupFn = keyboardDismissHandlerManager.push(callback);
    } else {
      cleanupFn();
    }
    return () => {
      cleanupFn();
    };
  }, [enabled, callback]);

  useBackHandler({ enabled, callback });
};

export function useBackHandler({ enabled, callback }: IParams) {
  useEffect(() => {
    let subscription: { remove: () => void } | null = null;
    
    const backHandler = () => {
      callback();
      return true;
    };

    if (enabled) {
      // Nova API (RN ≥0.65)
      subscription = BackHandler.addEventListener('hardwareBackPress', backHandler);
    }

    return () => {
      if (subscription) {
        subscription.remove();
      }
    };
  }, [enabled, callback]);
}
```

**Comment by afonsomsalvador** [comment]
After upgrading React Native to version **0.80**, I noticed that the traditional approach using `BackHandler.removeEventListener` no longer works as expected. Previously, I used to register and remove the event listener like this:

```tsx
useEffect(() => {
  BackHandler.addEventListener('hardwareBackPress', handleBackButtonClick);

  return () => {
    BackHandler.removeEventListener('hardwareBackPress', handleBackButtonClick);
  };
}, []);
```
However, this no longer removes the event correctly in React Native 0.80.

The only approach that currently works is:


```tsx
useEffect(() => {
  const backHandler = BackHandler.addEventListener(
    'hardwareBackPress',
    handleBackButtonClick
  );

  return () => {
    backHandler.remove(); // This works
  };
}, []);
```

In previous versions (e.g., 0.71, 0.72), calling `BackHandler.removeEventListener` would correctly remove the event listener.

**Comment by Rajputsachi** [comment]
> Same here, stuck here.

Any solution @mhaf4krr ?

**Comment by Yeasirarafat53** [comment]
I was previously using "react-native-modal": "^13.0.1" in my project, and I encountered the following error:

`_reactNative.BackHandler.removeEventListener is not a function (it is undefined)`

After investigating, I found that this issue was related to the usage of the deprecated BackHandler.removeEventListener method in the package.

To resolve this, I updated the package to the latest release candidate:

`"react-native-modal": "^14.0.0-rc.1"`

After the update, the error no longer occurs, and everything works as expected.

**Comment by barmanrajdeep** [comment]
[react-native-modal+13.0.1.patch](https://github.com/user-attachments/files/21830622/react-native-modal%2B13.0.1.patch)

If you are on react-native 0.77.x applying this patch will work

**Comment by QuangDung159** [comment]
> I was previously using "react-native-modal": "^13.0.1" in my project, and I encountered the following error:
> 
> `_reactNative.BackHandler.removeEventListener is not a function (it is undefined)`
> 
> After investigating, I found that this issue was related to the usage of the deprecated BackHandler.removeEventListener method in the package.
> 
> To resolve this, I updated the package to the latest release candidate:
> 
> `"react-native-modal": "^14.0.0-rc.1"`
> 
> After the update, the error no longer occurs, and everything works as expected.

You save my day

**Comment by ryanwilll** [comment]
Estava enfrentando um problema relacionado ao **react-native-modal**.  
Se a biblioteca estiver em uma versão inferior à `14`, esse erro pode ocorrer.

Para resolver, atualizei para a versão mais recente:  
`npm install react-native-modal@latest` (atualmente `14.0.0-rc.1`).

A principal mudança foi a forma de remover o listener do botão "voltar":

Antes (versões antigas):
```js
componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPress);
    if (this.didUpdateDimensionsEmitter) {
        this.didUpdateDimensionsEmitter.remove();
    }
    if (this.interactionHandle) {
        InteractionManager.clearInteractionHandle(this.interactionHandle);
        this.interactionHandle = null;
    }
}
```

Depois (>=14.0.0-rc.1):
```js
componentWillUnmount() {
    if (this.backHandler) {
        this.backHandler.remove();
        this.backHandler = null;
    }
    if (this.didUpdateDimensionsEmitter) {
        this.didUpdateDimensionsEmitter.remove();
    }
    if (this.interactionHandle) {
        InteractionManager.clearInteractionHandle(this.interactionHandle);
        this.interactionHandle = null;
    }
}
```

---

### 📌 English Version (EN)

I was facing an issue related to **react-native-modal**.  
If the library version is below `14`, this error may occur.

To fix it, I updated to the latest version:  
`npm install react-native-modal@latest` (currently `14.0.0-rc.1`).

The main change is how the back button listener is removed:

Before (older versions):
```js
componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackButtonPress);
    if (this.didUpdateDimensionsEmitter) {
        this.didUpdateDimensionsEmitter.remove();
    }
    if (this.interactionHandle) {
        InteractionManager.clearInteractionHandle(this.interactionHandle);
        this.interactionHandle = null;
    }
}
``` 

After (>=14.0.0-rc.1):
```js
componentWillUnmount() {
    if (this.backHandler) {
        this.backHandler.remove();
        this.backHandler = null;
    }
    if (this.didUpdateDimensionsEmitter) {
        this.didUpdateDimensionsEmitter.remove();
    }
    if (this.interactionHandle) {
        InteractionManager.clearInteractionHandle(this.interactionHandle);
        this.interactionHandle = null;
    }
}
```

**Comment by Ken-vdE** [comment]
Don't do this anymore:
```typescript
BackHandler.addEventListener('hardwareBackPress', this.handleBackButtonClick);
...
BackHandler.removeEventListener('hardwareBackPress', this.handleBackButtonClick);
```
Do this
```typescript
const backHandlerSubscription = BackHandler.addEventListener('hardwareBackPress', this.handleBackButtonClick);
...
backHandlerSubscription.remove();
```
As per https://reactnative.dev/docs/backhandler

**Comment by iway1** [comment]
this was fixed in @expo/react-native-action-sheet btw, if that's your issue just upgrade to 4.1.1
