### ISSUE TITLE
Compile erros on @react-navigation/stack using @types/react-native@0.70.X

### ISSUE THREAD

**Issue by gdogaru** [react-navigation/react-navigation#11019]
### Current behavior

After updating to react-native 0.70.X and @types/react-native@0.70.X , `tsc` fails
Here is a similar issue from react-native-gesture-handler:  https://github.com/software-mansion/react-native-gesture-handler/issues/2259

```

node_modules/@react-navigation/stack/src/types.tsx:110:12 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

110   current: Animated.AnimatedInterpolation;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:115:10 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

115   next?: Animated.AnimatedInterpolation;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:120:14 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

120   previous?: Animated.AnimatedInterpolation;
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:380:15 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

380     progress: Animated.AnimatedInterpolation;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:390:15 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

390     progress: Animated.AnimatedInterpolation;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:399:12 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

399   closing: Animated.AnimatedInterpolation;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:403:12 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

403   swiping: Animated.AnimatedInterpolation;
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:407:13 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

407   inverted: Animated.AnimatedInterpolation;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:459:15 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

459     progress: Animated.AnimatedInterpolation;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@react-navigation/stack/src/types.tsx:469:15 - error TS2314: Generic type 'AnimatedInterpolation<OutputT>' requires 1 type argument(s).

469     progress: Animated.AnimatedInterpolation;
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 10 errors in the same file, starting at: node_modules/@react-navigation/stack/src/types.tsx:110
```

### Expected behavior

compiles with RN 0.70.X

### Reproduction

https://github.com/software-mansion/react-native-gesture-handler/issues/2259

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use
- The rest do not matter

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.13
| @react-navigation/stack                | 6.3.4
| react-native                           | 0.70.6

**Comment by JCown** [comment]
Any updates on this? It would be nice to have a fix for `v5.x` version as well.

**Comment by zhiqingchen** [comment]
react native 0.71.X have the same problem

**Comment by zhiqingchen** [comment]
Maybe version 7.x will solve this problem

https://github.com/react-navigation/react-navigation/blob/7.x/packages/stack/src/types.tsx

**Comment by marioviana** [comment]
I'm having the same issue while using these dependencies:
`"@react-navigation/stack": "^5.1.1"`
`"react-native": "0.70.5"`

**Comment by xanderdeseyn** [comment]
Same issue. Anyone found a solution?

**Comment by tomgreco** [comment]
@react-navigation/core/src/types.tsx: Unexpected token, expected "?"

Similar issue on react-native 0.70.0

**Comment by monkey0722** [comment]
The type error issue with `Animated.AnimatedInterpolation` is supported in [@react-navigation/stack@6.3.17](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%406.3.17).
