### ISSUE TITLE
TypeScript types for createStackNavigator have gone missing in 5.2.7

### ISSUE THREAD

**Issue by jamesisaac** [react-navigation/react-navigation#7882]
I can't see how any change in the code would have caused this, so maybe a bug during the publish? Different environment on the most recent publish maybe?  cc @osdnk 

**Current Behavior**

- `yarn add @react-navigation/stack@5.2.7`
- Contents of `node_modules\@react-navigation\stack\lib\typescript\src\navigators\createStackNavigator.d.ts`:

```js
declare const _default: any;
export default _default;
```

**Expected Behavior**

- `yarn add @react-navigation/stack@5.2.6`
- Contents of `node_modules\@react-navigation\stack\lib\typescript\src\navigators\createStackNavigator.d.ts`:

```js
import { DefaultNavigatorOptions, StackRouterOptions, StackNavigationState } from '@react-navigation/native';
import { StackNavigationConfig, StackNavigationOptions, StackNavigationEventMap } from '../types';
declare type Props = DefaultNavigatorOptions<StackNavigationOptions> & StackRouterOptions & StackNavigationConfig;
declare function StackNavigator({ initialRouteName, children, screenOptions, ...rest }: Props): JSX.Element;
declare const _default: <ParamList extends Record<string, object | undefined>>() => import("@react-navigation/native").TypedNavigator<ParamList, StackNavigationState, StackNavigationOptions, StackNavigationEventMap, typeof StackNavigator>;
export default _default;
```

---

Maybe there are more differences too, this is just the one I ran into.  It introduces this error into the project:

```
error TS2347: Untyped function calls may not accept type arguments.

11 const Stack = createStackNavigator<RootStackParamList>();
```

**Comment by indralukmana** [comment]
I also found this issue when initiating migration to React Navigation 5. I followed the typing guides here (https://reactnavigation.org/docs/typescript ) but stuck on typing the `createStackNavigator`.

Currently working with `@react-navigation/stack@5.2.6` and the typing works.

**Comment by satya164** [comment]
I just published a new version of stack (5.2.8) which should fix it. Please give it a try.

**Comment by JonnyBurger** [comment]
Confirmed to be fixed 😃

**Comment by jamesisaac** [comment]
Yup that's fixed it, thanks!

**Comment by indralukmana** [comment]
Awesome stuff! installed with `yarn add @react-navigation/stack@latest`  which currently points to (5.2.8) and the types work. Thanks!

**Comment by bd-arc** [comment]
Could this also be an issue with versions `2.x.y` of the `react-navigation-stack` package?

For example, the `TransitionPreset` type can no longer be imported, whereas it was working up until version `2.0.1`.

**Comment by willcaul** [comment]
looks like bug has reappeared in version `5.2.12`

**Comment by rohan7chaudhary** [comment]
Still an issue in  version 5.3.8
