### ISSUE TITLE
For React-native 0.60.0 auto link, Android : null is not an object (evaluating 'RNGestureHandlerModule.State'. 

### ISSUE THREAD

**Issue by lehang123** [react-navigation/react-navigation#6055]
### Current Behavior

After running react-native run-android shows :
 null is not an object (evaluating 'RNGestureHandlerModule.State'. )

### Expected Behavior

no bug

### How to reproduce
react-native **unlink** react-native-gesture-handler 
(I have to, because the auto link, otherwise it builds fail)

simply run react-native run-android

then the bug shows up
(addition : I change my react native back to 0.59.0, and install as the instruction from the website, then it 
works fine. But I want to know is there a way to get it working on 0.60.0)
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.0
| react-native     |^0.60.0
| node             |v12.5.0
| npm or yarn      | npm 6.9.0

**Comment by IhorDudariev** [comment]
same issue

**Comment by satya164** [comment]
Please open the issue in the gesture handler repo since the issue is in that package: https://github.com/kmagiera/react-native-gesture-handler

If auto-link isn't working for you, you should link it manually as before.

**Comment by ivanzhang** [comment]
manual link still not work, looks it only support AndroidX, no support libs there :

> node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEvent.java:3: error: package android.support.v4.util does not exist
import android.support.v4.util.Pools;

**Comment by satya164** [comment]
You need to use jetifier for Android X https://github.com/mikehardy/jetifier
