### ISSUE TITLE
TypeError: _this._isStateful is not a function in react-native seed

### ISSUE THREAD

**Issue by Snare92** [react-navigation/react-navigation#5051]
react navigation doesn't work with react-native 0.57.1 generated from seed 
(react-native init AwesomeProject, cli version 2.0.1)

### Current Behavior

- just add react navigation to the project
- Include code from https://reactnavigation.org/docs/en/hello-react-navigation.html for StackNavigator
- app will Crash with error:

TypeError: _this._isStateful is not a function. (In '_this._isStateful()', '_this._isStateful' is undefined)

This error is located at:
    in NavigationContainer (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

NavigationContainer
    createNavigationContainer.js:80:10
constructClassInstance
    ReactNativeRenderer-dev.js:8039:26
updateClassComponent
    ReactNativeRenderer-dev.js:10474:8
performUnitOfWork
    ReactNativeRenderer-dev.js:14091:21
workLoop
    ReactNativeRenderer-dev.js:14129:41
renderRoot
    ReactNativeRenderer-dev.js:14226:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:15193:17
performWork
    ReactNativeRenderer-dev.js:15090:24
performSyncWork
    ReactNativeRenderer-dev.js:15047:14
requestWork
    ReactNativeRenderer-dev.js:14925:19
scheduleWork
    ReactNativeRenderer-dev.js:14711:16
scheduleRootUpdate
    ReactNativeRenderer-dev.js:15429:15
render
    ReactNativeRenderer-dev.js:16142:20
renderApplication
    renderApplication.js:59:34
run
    AppRegistry.js:101:10
runApplication
    AppRegistry.js:195:26
__callFunction
    MessageQueue.js:349:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:297:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17

### Expected Behavior

- app should render properly with StackNavigator

### How to reproduce

- create new project with react-native init AwesomeProject57
- add code mentioned here https://reactnavigation.org/docs/en/hello-react-navigation.html for StackNavigator
- start the app using react-native run-ios

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.1
| node             | 8.12.0
| yarn      | 1.9.4

**Comment by takunee** [comment]
the same problem

**Comment by brentvatne** [comment]
it's a bug with babel sorry there's nothing i can do to help
