### ISSUE TITLE
open drawer in header

### ISSUE THREAD

**Issue by nasim-fani** [react-navigation/react-navigation#6904]
**Current Behavior**

I'm using react-navigation version 5.
I have tab navigation and drawer navigation together.

I'm trying to add an icon in my header to open/close drawer:

   
        
 here is my custom right header for toggling the drawer:

    const HeaderRight = ({ navigation }) => {   
        return (
          <View style={{flexDirection: 'row'}}>
            <TouchableOpacity
            onPress={ () =>{ navigation.toggleDrawer()}}>  //here is the problem
              <Image source={require('./assets/images/icons/drawer.png')}/>
            </TouchableOpacity>
          </View>
        );}

    
this is my tab navigator:

    const Tab = createBottomTabNavigator();
    function AppTab() {
      return (
         <Tab.Navigator>         
            <Tab.Screen name="Category" component={Category} />    
            <Tab.Screen name="Home" component={Home}/>
          </Tab.Navigator>
       );}
    
  
drawer navigator:
 
        const Drawer = createDrawerNavigator();  
        function App() {
          return (    
              <Drawer.Navigator>
                <Drawer.Screen name="AppTab" component={AppTab} />
                <Drawer.Screen name="Notifications" component={NotificationsScreen} />
              </Drawer.Navigator>  
          );}

and my stack navigator to theme mix all:

    const Stack = createStackNavigator();
      export default function MyStack() {
      return (
        <NavigationContainer>
        <Stack.Navigator
        headerMode="screen"
         screenOptions={{
              headerRight: ({ navigation }) => (<HeaderRight navigation={navigation} />
            ),}} >
          <Stack.Screen name="Settings" component={Settings} />
        </Stack.Navigator>
        </NavigationContainer>
      );
    }

when I press the right header icon [![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/pHZIK.png

what I'm missing here?
the documents weren't really helpful

note:I have also try using dispatch but it didn't work:

> navigation.dispatch(DrawerActions.toggleDrawer())

**package.json:**

    {
      "name": "test",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "start": "react-native start",
        "test": "jest",
        "lint": "eslint ."
      },
      "dependencies": {
        "@react-native-community/async-storage": "^1.8.0",
        "@react-native-community/masked-view": "^0.1.6",
        "@react-navigation/bottom-tabs": "^5.0.5",
        "@react-navigation/drawer": "^5.0.5",
        "@react-navigation/native": "^5.0.5",
        "@react-navigation/stack": "^5.0.5",
        "moment": "^2.24.0",
        "randomcolor": "^0.5.4",
        "react": "16.9.0",
        "react-native": "0.61.5",
        "react-native-base64": "0.0.2",
        "react-native-gesture-handler": "^1.6.0",
        "react-native-image-slider": "^2.0.3",
        "react-native-reanimated": "^1.7.0",
        "react-native-safe-area-context": "^0.7.3",
        "react-native-screens": "^2.0.0-beta.4",
        "react-native-woocommerce-api": "^1.0.12"
      },
      "devDependencies": {
        "@babel/core": "^7.6.2",
        "@babel/runtime": "^7.6.2",
        "@react-native-community/eslint-config": "^0.0.5",
        "babel-jest": "^24.9.0",
        "eslint": "^6.5.1",
        "jest": "^24.9.0",
        "metro-react-native-babel-preset": "^0.56.0",
        "react-test-renderer": "16.9.0"
      },
      "jest": {
        "preset": "react-native"
      }
    }

**Comment by WoLewicki** [comment]
According to https://github.com/react-navigation/react-navigation/blob/4578849ebf48e39855b2dcbb84b5419e60846390/packages/stack/src/types.tsx#L174, the only prop passed to `headerRight` is `tintColor`. If you want to use the navigation in it, use `useNavigation` hook inside the component. Does it solve your problem?

**Comment by satya164** [comment]
You need to render your drawer navigator (`App` component) somewhere. The `MyStack` component should be a screen inside the `Drawer`.

**Comment by TheWirv** [comment]
> According to
> 
> https://github.com/react-navigation/react-navigation/blob/4578849ebf48e39855b2dcbb84b5419e60846390/packages/stack/src/types.tsx#L174
> 
> , the only prop passed to `headerRight` is `tintColor`. If you want to use the navigation in it, use `useNavigation` hook inside the component. Does it solve your problem?

That is true. I guess the following code would solve your problem:
```javascript
const Stack = createStackNavigator();
  export default function MyStack() {
  return (
    <NavigationContainer>
    <Stack.Navigator
    headerMode="screen"
     screenOptions={({ navigation}) => ({
          headerRight: () => (<HeaderRight navigation={navigation} />
        })} >
      <Stack.Screen name="Settings" component={Settings} />
    </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by aprilmintacpineda** [comment]
I used to be able to do this so easy before, now it's harder, why?

I used to be able to do:

```
Stack
  - Drawer
     - Stack
```

with ease with the old version, now it seems that it's become impossible? Any help would be appreciated...

**Comment by razaadeel** [comment]
For those who still didn't find any solution, I tried this and works fine. 
`options={({ navigation }) => ({
                        title: '',
                        headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}>
                            <FontAwesome5 name='bars' color='white' size={20} />
                        </TouchableOpacity>,
                        headerLeftContainerStyle: { paddingLeft: 10 }
                    })}`

**Comment by razaadeel** [comment]
This works fine in my case:
`options={({ navigation }) => ({
                        title: 'Products',
                        headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}>
                            <FontAwesome5 name='bars' color='white' size={20} />
                        </TouchableOpacity>,
                        headerLeftContainerStyle: { paddingLeft: 10 }
                    })}`

**Comment by plaporte** [comment]
> This works fine in my case:
> `options={({ navigation }) => ({ title: 'Products', headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>, headerLeftContainerStyle: { paddingLeft: 10 } })}`

This worked! Thank you. And so others are aware, you can substitute options for screenOptions and use this the exact same way on the stack navigator so you don't have to duplicate across all screens.

**Comment by aprilmintacpineda** [comment]
> This works fine in my case:
> `options={({ navigation }) => ({ title: 'Products', headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>, headerLeftContainerStyle: { paddingLeft: 10 } })}`

Did you put this prop in `Stack.Navigator`? Would be great if you can provide more snippets...

**Comment by plaporte** [comment]
> > This works fine in my case:
> > `options={({ navigation }) => ({ title: 'Products', headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>, headerLeftContainerStyle: { paddingLeft: 10 } })}`
> 
> Did you put this prop in `Stack.Navigator`? It would be great if you can provide more snippets...

Yes... change options to screenOptions and put it in the Stack.Navigator like so:
`<DashboardStack.Navigator 
   screenOptions={({ navigation }) => ({ 
      title: 'Products', 
      headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> 
      <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>,
       headerLeftContainerStyle: { paddingLeft: 10 } }
   )}
>
    <DashboardStack.Screen name="Dashboard" component={DashboardTabsScreen} />
    <DashboardStack.Screen name="Info" component={LeagueInfoScreen} />
  </DashboardStack.Navigator>`

**Comment by lewandy** [comment]
Hello, I resolve it using the code below for open the drawer.

` navigation.dispatch(DrawerActions.toggleDrawer()); `

**Comment by Wellers0n** [comment]
this worked for me.

```
import { DrawerActions } from '@react-navigation/native';

headerLeft: () => (
   <TouchableOpacity style={styles.bars} onPress={() => navigation.dispatch(DrawerActions.toggleDrawer())}>
      <Icon name="bars" size={25} color="#fff" />
   </TouchableOpacity>
),
```

**Comment by CarlosIMartin** [comment]
> This works fine in my case:
> `options={({ navigation }) => ({ title: 'Products', headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>, headerLeftContainerStyle: { paddingLeft: 10 } })}`

Works well, thanks!

**Comment by bangmai** [comment]
> This works fine in my case:
> `options={({ navigation }) => ({ title: 'Products', headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>, headerLeftContainerStyle: { paddingLeft: 10 } })}`

thanks. this work.

**Comment by Mudassirraza912** [comment]
> this worked for me.
> 
> ```
> import { DrawerActions } from '@react-navigation/native';
> 
> export const option = ({navigation}): Object => {
>     return {
>         headerLeft: () => (
>             <TouchableOpacity style={styles.bars} onPress={() => navigation.dispatch(DrawerActions.toggleDrawer())}>
>                 <Icon name="bars" size={25} color="#fff" />
>             </TouchableOpacity>
>         ),
>     }
> }
> ```

Please tell me your '@react-navigation/native' version because this code not working in "@react-navigation/native": "^5.7.3"

**Comment by Deepak9811** [comment]
> screenOptions={({ navigation }) => ({ 
>       title: 'Products', 
>       headerLeft: () => <TouchableOpacity onPress={() => navigation.toggleDrawer()}> 
>       <FontAwesome5 name='bars' color='white' size={20} /> </TouchableOpacity>,
>        headerLeftContainerStyle: { paddingLeft: 10 } }
>    )}

 ERROR  TypeError: navigation.toggleDrawer is not a function. (In 'navigation.toggleDrawer()', 'navigation.toggleDrawer' is undefined)

**Comment by mwaleed-39** [comment]
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, View } from 'react-native';
import React from 'react';
import Reg_form from './Frontend/Components/RegForm';
import Login_form from './Frontend/Components/Signin';
import ForgotPassword from './Frontend/Components/ForgotPassword';
import { ApplicationProvider, Layout, Text } from '@ui-kitten/components';
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import {
createDrawerNavigator,
DrawerContentScrollView,
DrawerItemList,
DrawerItem,
} from '@react-navigation/drawer';
import * as eva from '@eva-design/eva';
import ChangePassword from './Frontend/Components/ChangePassword';
import VerifyOTP from './Frontend/Components/VerifyOTP';
import Home from './Frontend/Components/Home Screen';
import Profile from './Frontend/Components/Profile';
import Icon from 'react-native-vector-icons'
const Stack = createNativeStackNavigator();
const Drawer = createDrawerNavigator();

const CustomDrawer = props => {

return (
<View style={{ flex: 1 }}>
<DrawerContentScrollView {...props}>
<View
style={{
alignSelf: "center",
padding: 20,

      }}
    >
      <View>
        <Text style={{ fontSize: 18, fontWeight: "bold" }}> App</Text>
      </View>

    </View>
    <DrawerItemList {...props} />
    <LogoutButton iconName="sign-out" color="black" />
  </DrawerContentScrollView>

</View>
);
};

function DrawerRoutes() {

return (

<Drawer.Navigator initialRouteName="Home"

  drawerContent={props => <CustomDrawer {...props} />}
>

  <Drawer.Screen name="Home" component={Home}

    options={{
      headerShown: true,
      
      title: 'Home',
      drawerIcon: ({ focused, size }) => (
        <Icon
          name="home"
          size={size}
          color='black'

        />

      )
    }}
  />
  <Drawer.Screen name="Profile" component={Profile}

    options={{
      headerShown: true,
      title: 'Profile',
      drawerIcon: ({ focused, size }) => (
        <Icon
          name="user"
          size={size}
          color='black'

        />

      )
    }}
  />




</Drawer.Navigator>
);
}

export default function App() {
return (
<ApplicationProvider {...eva} theme={eva.light}>

<NavigationContainer>
<Stack.Navigator>
          <Stack.Screen name="Registration" component={Reg_form} />
          <Stack.Screen name="Log In" component={Login_form}/>
          <Stack.Screen name="Forgot" component={ForgotPassword}/>
          <Stack.Screen name="Password" component={ChangePassword}/>
          <Stack.Screen name="Verification" component={VerifyOTP}/>
          <Stack.Screen name="Home" component={Home}  />
          <Stack.Screen name="DrawerRoutes" component={DrawerRoutes}/>
</Stack.Navigator>

); }
When we log in to the App, then navigate into the Home Screen. Then we have not visible Drawer navigation
